package person.li.dao;

import person.li.model.UserRoleDto;

public interface UserRoleDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pkUserRole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    int insert(UserRoleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    int insertSelective(UserRoleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    UserRoleDto selectByPrimaryKey(String pkUserRole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRoleDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRoleDto record);
}